### ISSUE TITLE
Compilation Failure at times

### ISSUE THREAD

**Issue by kroseberry13SIT** [Scarabyte/SSW690-Project#53]
The compiler is unable to find the ComparisonFrameRenderer class some of the time. There is probably a dependency that needs to be set up.

**Comment by bsapana** [comment]
I am getting below error about deprecated API in MainActivity.java

C:\Sapana\SSW690-Project\src\opencv_proj\app\src\main\java\com\example\backseatdrivers\MainActivity.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

**Comment by Scarabyte** [comment]
@bsapana That one is a warning, but I don't think it prevents executing the app. Using a deprecated API means that the function will be removed sometime in the future, but at least for right now it still works.
@kroseberry13SIT I haven't (yet?) seen that error, but I didn't find any instances of ComparisonFrameRenderer in my setup.

**Comment by Scarabyte** [comment]
Looks like ProgressBar is the alternative: https://stackoverflow.com/questions/45373007/progressdialog-is-deprecated-what-is-the-alternate-one-to-use

And, according to the Android Developers site, seems you can also use a notification instead: https://developer.android.com/reference/android/app/ProgressDialog

**Comment by Scarabyte** [comment]
Okay, just seen the original bug while trying to test Pull Request #54 

error: cannot find symbol class ComparisonFrameRender

**Comment by Scarabyte** [comment]
Trying to track this down...
OnCameraFrameRender.java was introduced in commit 287732e35b2f5f16d194835370763358dc858c02

**Comment by Scarabyte** [comment]
Seems some of the methods in ProgressBar require API 26 to achieve equivalent functionality to what we're doing with ProgressDialog - currently our min API is 21. It may not be bad to leave it for now, but we can consider updating it as an enhancement later when the app is more complete.
